# Generated by Django 6.1 on 2026-09-28 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('shared', '0004_remove_entity_status_entity_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('NL', 'New Lead'), ('OL', 'Open Lead'), ('QO', 'Quoted Lead'), ('IP', 'In Progress'), ('LL', 'Lost Lead'), ('WL', 'Won Lead')], default='NL')),
                ('stage', models.CharField(choices=[('N', 'New'), ('P', 'Prospected'), ('Q', 'Qualified'), ('E', 'Engaged'), ('A', 'Awaiting'), ('C', 'Closed')], default='N')),
                ('size', models.IntegerField(blank=True, default=1, null=True)),
                ('qualifying_score', models.SmallIntegerField(blank=True, null=True)),
                ('temperature', models.CharField(choices=[('I', 'Ice'), ('CD', 'Cold'), ('CL', 'Cool'), ('N', 'Neutral'), ('LW', 'Lukewarm'), ('W', 'Warm'), ('H', 'Hot')], default='N')),
                ('responsiveness', models.DateTimeField(blank=True, null=True)),
                ('turn', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='shared.company')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='shared.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
