# Generated by Django 6.1.2 on 2026-10-06 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_lead_created_at_lead_created_by_lead_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='basis',
            field=models.CharField(choices=[('B', 'Both'), ('A', 'Accrual only'), ('C', 'Cash only')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='cash_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_payment', to='accounting.journalentry'),
        ),
    ]
