# Generated by Django 6.1 on 2026-09-08 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('ASSET', 'Asset'), ('STOCK', 'Stock'), ('CONSUMABLE', 'Consumable'), ('COMPONENT', 'Component')])),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('CONTAINS', 'Contains'), ('REPLACEMENT', 'Replacement'), ('ACCESSORY', 'Accessory'), ('COMPATIBLE', 'Compatible'), ('DEPENDENCY', 'Dependency')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=13)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_relationships', to='inventory.item')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_relationships', to='inventory.item')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('parent', 'child', 'relationship_type'), name='unique_item_relationship')],
            },
        ),
    ]
