# Generated by Django 6.1 on 2026-09-13 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='code',
        ),
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='depreciate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='lifespan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='lifeunits',
            field=models.CharField(blank=True, choices=[('Y', 'Years'), ('M', 'Months'), ('D', 'Days')], null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='obsoleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tag',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StockTakeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_days', models.PositiveIntegerField(default=30)),
                ('start_date', models.DateField()),
                ('next_due', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_take_schedule', to='inventory.item')),
            ],
        ),
    ]
