# Generated by Django 6.1 on 2026-09-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestore', '0001_initial'),
        ('inventory', '0002_remove_item_code_item_cost_item_depreciate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='+', to='filestore.storedfile'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('STOCK', 'Stock'), ('CONSUMABLE', 'Consumable'), ('COMPONENT', 'Component')], default='STOCK'),
        ),
    ]
