# Generated by Django 6.1 on 2026-09-13 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entity',
            name='status',
            field=models.CharField(choices=[('NL', 'New Lead'), ('OL', 'Open Lead'), ('HL', 'In Progress'), ('CL', 'Lost Lead'), ('C', 'Customer'), ('S', 'Supplier'), ('UD', 'Undefined')], default='UD'),
        ),
    ]
