# Generated by Django 6.1 on 2026-09-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_entity_owner_entity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
