# Generated by Django 6.1 on 2026-09-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_entity_name_alter_entity_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='status',
        ),
        migrations.AddField(
            model_name='entity',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.CharField(choices=[('I', 'Individual'), ('O', 'Organization'), ('S', 'Supplier'), ('P', 'Partner'), ('D', 'Distributor'), ('R', 'Retailer')], max_length=1),
        ),
    ]
