# Generated by Django 6.1.2 on 2026-10-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_businessrole_industry_source_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='accounting_basis',
            field=models.CharField(choices=[('A', 'Accrual'), ('C', 'Cash')], default='A', max_length=1),
        ),
    ]
